version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: survey-app
    networks:
      - shared-network
    ports:
      - "8089:8089"

networks:
  shared-network:
    external: true
