version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: very_hard_password!
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge
